### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by kex243** [voidstrike/ASGIT#2]
At first I want to thank you a lot for the job. According to tests it seems that this arch has the best quality over all. Surprised that there are no party around. But for now I just can not run the code for both pix2pix attn and cyclegan attn.

```
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 303, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 141, in forward
    _, attn_A = self.netD_B(self.real_A)
ValueError: not enough values to unpack (expected 2, got 1)
``` in both cases. Im trying to run it with the same env as AGGAN.
Not sure if it is about my Conda, but may this bug be caused by CUDA 11 instead of 9? Torch also is latest. Shall I try to rebuild env and downgrade cuda to 9?

**Comment by kex243** [comment]
seems I ve been runing code without all flags. But then appears this:
```
 self.fake_B = self.netG_A(self.real_A * (1. + self.attn_A))
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3
```

**Comment by voidstrike** [comment]
> seems I ve been runing code without all flags. But then appears this:
> 
> ```
>  self.fake_B = self.netG_A(self.real_A * (1. + self.attn_A))
> RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3
> ```

**Comment by voidstrike** [comment]
Mis-click

**Comment by voidstrike** [comment]
@kex243 Thanks for your interest! 
Unfortunately, I do not fully get your question. Could you please provide the command line and the dataset (The shape of the image would be sufficient) you used? 
I'm not sure about the Torch & CUDA version, yet the error msg is not about them.

**Comment by voidstrike** [comment]
> seems I ve been runing code without all flags. But then appears this:
> 
> ```
>  self.fake_B = self.netG_A(self.real_A * (1. + self.attn_A))
> RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3
> ```

For this specific error, could you please try "--mask_size 256"? Looks like this issue is caused by the inconsistent shape between the input image and the attention mask.

**Comment by kex243** [comment]
Sorry for not replying for a week. 
python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodASGIT
thats the code I run from instruction and get the error, it is connected to option line with 256 default resolution and gives other errors ([320] for example) if to change the value. If I change resolution of my dataset to 128 and so in options I get 
`E:\miniconda3.2\lib\site-packages\torch\nn\functional.py:3122: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_model.py", line 239, in optimize_parameters
    self.aux_data.update_attn_map(self.attn_A_index, self.tmp_attn_A.detach_(), True)
  File "D:\pix2pix\ASGIT-main\data\aux_dataset.py", line 29, in update_attn_map
    self.A_attns[idx] = tgt_tensor
RuntimeError: shape mismatch: value tensor of shape [256, 256] cannot be broadcast to indexing result of shape [1, 1, 128, 128]
thats for attn version 1.
If trying to use v2 I get
----------------- Options ---------------
               batch_size: 1
                    beta1: 0.5
          checkpoints_dir: ./checkpoints
                   concat: alpha                                [default: rmult]
           continue_train: False
                crop_size: 128
                 dataroot: D:\pix2pix\ASGIT-main\datasets\bad2good      [default: None]
             dataset_mode: unaligned
                direction: AtoB
              display_env: main
             display_freq: 400
               display_id: 1
            display_ncols: 4
             display_port: 8097
           display_server: http://localhost
          display_winsize: 256
                    epoch: latest
              epoch_count: 1
                 gan_mode: lsgan
                  gpu_ids: 0
                init_gain: 0.02
                init_type: kaiming
                 input_nc: 3
                  isTrain: True                                 [default: None]
                 lambda_A: 10.0
                 lambda_B: 10.0
          lambda_identity: 0.0
                load_iter: 0                                    [default: 0]
                load_size: 128
                       lr: 0.0002
           lr_decay_iters: 50
                lr_policy: linear
                mask_size: 128
         max_dataset_size: inf
                    model: attn_cycle_gan_v2                    [default: cycle_gan]
               n_layers_D: 3
                     name: bad2goodASGIT                        [default: experiment_name]
                      ndf: 64
                     netD: posthoc_attn_v2                      [default: basic]
                     netG: resnet_9blocks
                      ngf: 64
                    niter: 100
              niter_decay: 100
               no_dropout: True
                  no_flip: False
                  no_html: False
                     norm: instance
              num_threads: 4
                output_nc: 3
                    phase: train
                pool_size: 50
               preprocess: scale_width_and_crop
               print_freq: 100
                 rec_coef: 0.5
                       s1: 32
                       s2: 16
             save_by_iter: False
          save_epoch_freq: 5
         save_latest_freq: 5000
           serial_batches: False
                   suffix:
         update_html_freq: 1000
                  use_rec: False
               use_warmup: False
                  verbose: False
             warmup_epoch: 30
----------------- End -------------------
dataset [UnalignedDataset] was created
The number of training images = 3894
initialize network with kaiming
initialize network with kaiming
initialize network with kaiming
initialize network with kaiming
model [AttnCycleGANV2Model] was created
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 11.381 M
[Network G_B] Total number of parameters : 11.381 M
[Network D_A] Total number of parameters : 2.765 M
[Network D_B] Total number of parameters : 2.765 M

Setting up a new session...
create web directory ./checkpoints\bad2goodASGIT\web...
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 303, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 147, in forward
    self.fake_B = self.netG_A(torch.cat((self.real_A, attn_A.detach()), 1))  # X -> G(X) = Y'
AttributeError: 'tuple' object has no attribute 'detach'`
I just remember that I've fixed this bug last week with a lot of code deletion in  v2_model.py, but I just hadn't saved the result and even deleted all the examples of images output for some reason. But saved model files shows me that it has been working. I don't even remember why I didn't used ASGAN instead of AGGAN for now. (Except for AGGAN runs =) But your visual result and image preworking from pix2pixHD tithes me a lot.
In the end I wanted to use this or any other cyclegan as enhancer for pix2pixHD output thats very raw. So, I want to use it with aligned dataset. Maybe you have some ideas how to use your code for aligned data? At least original cylcegan had such mode if use aligned data and flag it in options.  It still has two generators and D, but it works. Tried to use aligned dataset there too, but it shows another error. Maybe all of them caused by my new env. I'll try to fix something and will write if get something. Thanks in advance.

**Comment by kex243** [comment]
if to use python train_attn.py --netG resnet_9blocks --netD posthoc_attn_v2 --model attn_cycle_gan_v2 _--concat none_ --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodASGIT

it gets 

Setting up a new session...
create web directory ./checkpoints\bad2goodASGIT\web...
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 307, in optimize_parameters
    self.backward_G()             # calculate gradients for G_A and G_B
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_v2_model.py", line 285, in backward_G
    self.loss_G_A = self.criterionGAN(dis_A_res, True)
  File "D:\pix2pix\ASGIT-main\models\networks.py", line 297, in __call__
    target_tensor = self.get_target_tensor(prediction, target_is_real)
  File "D:\pix2pix\ASGIT-main\models\networks.py", line 284, in get_target_tensor
    return target_tensor.expand_as(prediction)
TypeError: expand_as(): argument 'other' (position 1) must be Tensor, not tuple

**Comment by kex243** [comment]
Also, tried mask 256. It works. Will try to use aligned mode. Sorry for disturbing with issues, just handn't seen this flag in options at all.

**Comment by voidstrike** [comment]
> Also, tried mask 256. It works. Will try to use aligned mode. Sorry for disturbing with issues, just handn't seen this flag in options at all.

Looks like the code is running now?
What do you mean by the aligned dataset? Are you trying to say a supervised translation?
To be honest, our framework offers a marginal improvement over pix2pix in a supervised setting.

**Comment by kex243** [comment]
Yes, supervised. But it shows error below in ver2 in both aligned and unaligned modes.
If to use 
`python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodAligned  --mask_size 256 --crop_size 256 --preprocess crop --dataset_mode aligned`
it gives 
`Setting up a new session...
create web directory ./checkpoints\bad2goodAligned\web...
Traceback (most recent call last):
  File "train_attn.py", line 99, in <module>
    model.set_input(data)  # unpack data from dataset and apply preprocessing
  File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_model.py", line 97, in set_input
    self.attn_A_index = input['ADX' if AtoB else'BDX']
KeyError: 'ADX'`

**Comment by voidstrike** [comment]
> Yes, supervised. But it shows error below in ver2 in both aligned and unaligned modes.
> If to use
> `python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodAligned --mask_size 256 --crop_size 256 --preprocess crop --dataset_mode aligned`
> it gives
> `Setting up a new session... create web directory ./checkpoints\bad2goodAligned\web... Traceback (most recent call last): File "train_attn.py", line 99, in <module> model.set_input(data) # unpack data from dataset and apply preprocessing File "D:\pix2pix\ASGIT-main\models\attn_cycle_gan_model.py", line 97, in set_input self.attn_A_index = input['ADX' if AtoB else'BDX'] KeyError: 'ADX'`

Ohh, I see.
So, actually, you want to train a CycleGAN-like framework without L1Loss, right? We didn't try our framework with such configuration (For supervised translation, we used pix2pix_attn_model -- well, that code is even worse).
Anyway, back to your question. You said you use `attn_cycle_gan_v2` but the command line looks different, is that a typo?
The error msg says "KeyError: 'ADX'", but 'ADX' is available in [here](https://github.com/voidstrike/ASGIT/blob/main/data/unaligned_dataset.py#L64).
* Maybe you can change 'DX' to ('ADX' and 'BDX') [here](https://github.com/voidstrike/ASGIT/blob/main/data/aligned_dataset.py#L56)

**Comment by kex243** [comment]
Yes, probably that's what I've been trying to do. I' ve seen this file (pix2pix_attn_model) but just don't have reference how to use it. Can you help me with code as shown examples for cycleGAN? I'm kinda stupid pirate that borrows code without understanding =). 

python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model pix2pix_attn  --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodASGIT --dataset_mode aligned --mask_size 256 --crop_size 256 --display_winsize 256 --load_size 256 --dataset_mode aligned
gives 
E:\miniconda3.2\lib\site-packages\torch\nn\functional.py:3122: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 141, in optimize_parameters
    self.aux_data.update_attn_map(self.attn_A_index, self.tmp_attn.detach(), True)
  File "D:\pix2pix\ASGIT-main\data\aux_dataset.py", line 29, in update_attn_map
    self.A_attns[idx] = tgt_tensor
RuntimeError: shape mismatch: value tensor of shape [256, 256] cannot be broadcast to indexing result of shape [1, 1, 32, 32]

if to change 256 size to 512 it gives 
create web directory ./checkpoints\bad2goodASGIT\web...
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 130, in optimize_parameters
    self.forward()                   # compute fake images: G(A)
  File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 101, in forward
    self.fake_B = self.netG(self.real_A * (1. + concat_attn_A))
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3

**Comment by voidstrike** [comment]
> Yes, probably that's what I've been trying to do. I' ve seen this file (pix2pix_attn_model) but just don't have reference how to use it. Can you help me with code as shown examples for cycleGAN? I'm kinda stupid pirate that borrows code without understanding =).
> 
> python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model pix2pix_attn --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodASGIT --dataset_mode aligned --mask_size 256 --crop_size 256 --display_winsize 256 --load_size 256 --dataset_mode aligned
> gives
> E:\miniconda3.2\lib\site-packages\torch\nn\functional.py:3122: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
> "See the documentation of nn.Upsample for details.".format(mode))
> Traceback (most recent call last):
> File "train_attn.py", line 100, in
> model.optimize_parameters() # calculate loss functions, get gradients, update network weights
> File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 141, in optimize_parameters
> self.aux_data.update_attn_map(self.attn_A_index, self.tmp_attn.detach(), True)
> File "D:\pix2pix\ASGIT-main\data\aux_dataset.py", line 29, in update_attn_map
> self.A_attns[idx] = tgt_tensor
> RuntimeError: shape mismatch: value tensor of shape [256, 256] cannot be broadcast to indexing result of shape [1, 1, 32, 32]
> 
> if to change 256 size to 512 it gives
> create web directory ./checkpoints\bad2goodASGIT\web...
> Traceback (most recent call last):
> File "train_attn.py", line 100, in
> model.optimize_parameters() # calculate loss functions, get gradients, update network weights
> File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 130, in optimize_parameters
> self.forward() # compute fake images: G(A)
> File "D:\pix2pix\ASGIT-main\models\pix2pix_attn_model.py", line 101, in forward
> self.fake_B = self.netG(self.real_A * (1. + concat_attn_A))
> RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3

For `attn_cyclegan` (w/o L1 Loss), can you try this one:
python train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan_v2 --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodAligned --mask_size 256 --crop_size 256 --preprocess crop

For `pix2pix_attn` (w L1 Loss), you may need to modify the code. (Since it's not our major task, we have some parameters hardcoded). [Here](https://github.com/voidstrike/ASGIT/blob/main/models/pix2pix_attn_model.py#L64), change 32 to 256 should solve your current error.

I believe you have played with the official CycleGAN repo. Just a reminder, an unaligned dataset has two sub-dirs (e.g. D:\pix2pix\ASGIT-main\datasets\bad2good\trainA and D:\pix2pix\ASGIT-main\datasets\bad2good\trainB), and an aligned dataset only has one sub-dir (D:\pix2pix\ASGIT-main\datasets\bad2good\train\).

**Comment by kex243** [comment]
Thanks, adding ADX and BDX both as index helped to start traning with this. `train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodAligned  --mask_size 256 --crop_size 256 --preprocess crop --dataset_mode aligned` and it uses aligned "doubled" images set as input.
pix2pix attn still gives
`RuntimeError: shape mismatch: value tensor of shape [256, 256] cannot be broadcast to indexing result of shape [1, 1, 32, 32]`

**Comment by voidstrike** [comment]
> Thanks, adding ADX and BDX both as index helped to start traning with this. `train_attn.py --netG resnet_9blocks --netD posthoc_attn --model attn_cycle_gan --concat rmult --dataroot D:\pix2pix\ASGIT-main\datasets\bad2good --name bad2goodAligned --mask_size 256 --crop_size 256 --preprocess crop --dataset_mode aligned` and it uses aligned "doubled" images set as input.
> pix2pix attn still gives
> `RuntimeError: shape mismatch: value tensor of shape [256, 256] cannot be broadcast to indexing result of shape [1, 1, 32, 32]`

Sorry for the confusion. I just updated the previous response.
Are you saying it's still not working even the code is modified?

**Comment by kex243** [comment]
Changing this line of code doesnt help, if I change it to 256 (or 128, just as all other parameters like crop and attention mask size) it overload 8gb of memory, If to change crop size and this line of code from 32 to 64 it gives same error with different parameters 
`RuntimeError: shape mismatch: value tensor of shape [512, 512] cannot be broadcast to indexing result of shape [1, 1, 64, 64]`
But, if to change all parameters to 128 and make params `7000, 7000, self.gpu_ids[0], mask_size=16)` it shows anotehr error:
```
File "E:\miniconda3.2\lib\site-packages\torch\nn\functional.py", line 1995, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])

```
with lots of pytorch erros before last line.
Sorry for bothering with very specific case. Maybe I shall close issue if you don't want to support such thing. But before I wanted to ask about your model before I tried to train it. If to compare to pix2pixHD, its model with whole videomemory used in traning gives on the output 1gb generator model size. But if to compare to your model, it also consumes a lot of memory while traning (yes, two generatros and D in cycle gan) but checkpoint G size is only 44mb with default 64 ngf. Does it mean that this model is worse than pix2pixHD in some specific cases like a lot of multi-domain translations or creating images from maps? Or is it used only for one domain translation and not specified to transform many types of objects into another? (if not to make difference to supervised and non-supervised traning). There is also such thing as STAR-gan and it also uses this buzz-word (at least for my level of competence =) "attention". STAR-gan also eats a lot of memory and this make it less useful for practical use if to compare even with p2pHD. Your model shows preview with quality overwhelming them all, thats why Im so interested in this. Maybe I don't understand something and I must look for another model? Final target- adding more details to blurred pix2pixHD output and just now Im thinking that this problem is close to image translation with "attention" to details and trying to divide the problem into two generators and just were looking for best solution for enhancer. Thatas why I want to run the pix2pix atten model.

**Comment by voidstrike** [comment]
> Changing this line of code doesnt help, if I change it to 256 (or 128, just as all other parameters like crop and attention mask size) it overload 8gb of memory, If to change crop size and this line of code from 32 to 64 it gives same error with different parameters
> `RuntimeError: shape mismatch: value tensor of shape [512, 512] cannot be broadcast to indexing result of shape [1, 1, 64, 64]`
> But, if to change all parameters to 128 and make params `7000, 7000, self.gpu_ids[0], mask_size=16)` it shows anotehr error:
> 
> ```
> File "E:\miniconda3.2\lib\site-packages\torch\nn\functional.py", line 1995, in _verify_batch_size
>     raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])
> ```
> 
> with lots of pytorch erros before last line.
> Sorry for bothering with very specific case. Maybe I shall close issue if you don't want to support such thing. But before I wanted to ask about your model before I tried to train it. If to compare to pix2pixHD, its model with whole videomemory used in traning gives on the output 1gb generator model size. But if to compare to your model, it also consumes a lot of memory while traning (yes, two generatros and D in cycle gan) but checkpoint G size is only 44mb with default 64 ngf. Does it mean that this model is worse than pix2pixHD in some specific cases like a lot of multi-domain translations or creating images from maps? Or is it used only for one domain translation and not specified to transform many types of objects into another? (if not to make difference to supervised and non-supervised traning). There is also such thing as STAR-gan and it also uses this buzz-word (at least for my level of competence =) "attention". STAR-gan also eats a lot of memory and this make it less useful for practical use if to compare even with p2pHD. Your model shows preview with quality overwhelming them all, thats why Im so interested in this. Maybe I don't understand something and I must look for another model? Final target- adding more details to blurred pix2pixHD output and just now Im thinking that this problem is close to image translation with "attention" to details and trying to divide the problem into two generators and just were looking for best solution for enhancer. Thatas why I want to run the pix2pix atten model.

What GPU do you use? I didn't worry about the GPU mem because the model is trained on a GPU with 48GB memory, and I do remember there are some memory issues if I ran the code on an RTX 1080ti. Since the batch_size is already 1, can you try another GPU is possible? (But this is weird, CycleGAN should consume more GPU mem).

The error message seems caused by the batch_norm, batch_norm layer requires batch_size > 1 in the training phase. As I said, our model does not perform well in the supervised translation thus we did the supervised translation experiment with lots of hardcode, really sorry about that. (But this is weird too, the default setting of norm should be "instance", see [here](https://github.com/voidstrike/ASGIT/blob/main/models/pix2pix_attn_model.py#L34))

For the rest questions, I'm not sure whether I interpret them correctly, but anyway.
1. Although I don't think pix2pix and pix2pixHD have much difference when the input image is small. We compared with pix2pix, not pix2pixHD.
2. Does pix2pixHD support multi-domain translation? I thought only StarGAN does that when I wrote the code. Our model does not support multi-domain translation, it's just an AtoB.

**Comment by kex243** [comment]
yep, 8 gb of 1080. Thanks a lot for for helping. Probably I just mess with meaning of multi-domain, as for me - it is possibility it converts one map into one type of object and anonter map into second object (correctly detecting both from map or even from not converted to mag original image), instead of only converting apples to oranges, only horse to zebras. More as facades dataset with different labels. I will be trying to run code later and will sign in case of something. Thanks.
Actualy, pix2pixHD can be trained to outperform pix2pix and other models if to run it with very low learning rate after default 0.0002, up 10^5-10^8 as I tested. And if time is not an issue as memory.
